### ISSUE TITLE
Transfer code to PyTorch

### ISSUE THREAD

**Issue by sincRK** [DIAGNijmegen/pathology-he-auto-augment#2]
Hey, thanks for the hard work. I want to adapt the code for use in a PyTorch model but can't find any explicit license and therefore have to assume the code is not free for addition. Could you adapt/specify your license to allow me and others to build on your code?

**Comment by KhrystynaFaryna** [comment]
Done.

**Comment by sincRK** [comment]
Thanks a lot:)
