### ISSUE TITLE
Great paper and great repo but why tensorflow

### ISSUE THREAD

**Issue by TumVink** [DIAGNijmegen/pathology-he-auto-augment#3]
As title ;(

**Comment by KhrystynaFaryna** [comment]
Those were the days, my friend:) The randaugment-related stuff and well as augmentations are independent of a framework. You can just keep everything augmentation related, use a pytorch dataloader and apply distort_image_with_randaugment(image, m, n, ra_type) function to each image/patch within the dataloader:)
